server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml

